-- Generated by tools/load-canton.mjs from OpenStreetMap (ODbL): Puntarenas > Coto Brus. Do not edit by hand.
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'r3223028', 'Puntarenas', 'province', null, 7.91830, -84.90689, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'r6265593', 'Coto Brus', 'canton', (select id from public.geo_places where osm_ref = 'r3223028'), 8.88970, -82.90924, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'r8476592', 'Limoncito', 'district', (select id from public.geo_places where osm_ref = 'r6265593'), 8.85152, -83.04689, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n4357682049', 'Limoncito', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.83029, -83.01637, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n8427266663', 'La Casona', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.83677, -83.07402, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5784749025', 'Santa Rita', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.82742, -82.99778, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n9793480946', 'Santa Marta', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.87572, -83.08255, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12155640229', 'Villa Palacios', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.82740, -83.06862, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12155640230', 'Copey Arriba', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.81583, -83.06088, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12155640231', 'Copey Abajo', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.82693, -83.05012, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5784749024', 'San Rafael', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.83637, -83.00795, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5784749032', 'Manchuria', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.85457, -83.01187, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5784749033', 'Alto Aguacate', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.84549, -83.03567, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5784749034', 'La Unión', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.85137, -83.04615, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5784749035', 'Brusmalis', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.83329, -83.04782, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5784749036', 'San Gerardo', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.86052, -83.06783, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n11998094329', 'Alto Limoncito', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.83162, -83.00390, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n11998094330', 'San Juan', 'locality', (select id from public.geo_places where osm_ref = 'r8476592'), 8.82195, -83.01308, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'r8476640', 'San Vito', 'district', (select id from public.geo_places where osm_ref = 'r6265593'), 8.83999, -82.97838, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n834239350', 'San Vito', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.82077, -82.97038, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n2520660566', 'Linda Vista', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.80400, -82.95689, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n3643294663', 'Aguas Claras', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.85289, -82.96563, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154026090', 'Danto', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.83983, -82.98557, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154584507', 'Lourdes', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.82634, -82.93852, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154587994', 'Santa Clara', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.80594, -82.99090, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154587995', 'Torre Alta', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.79934, -82.97844, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154625637', 'Bajo Reyes', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.85794, -82.99428, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437237318', 'San Joaquín', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.82539, -82.95360, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437268717', 'Las Juntas', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.85219, -82.94822, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437269052', 'La Isla', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.83212, -82.96197, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n2889591160', 'Los Pioneros', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.83117, -82.97349, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5784836172', 'Bajo Venado', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.87736, -82.98628, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5784836173', 'Piedra Pintada', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.86697, -82.96890, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n7387488330', 'María Auxiliadora', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.82067, -82.96732, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n7387488331', 'Canadá', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.83612, -82.97211, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n7387488332', 'La Meseta', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.81418, -82.97259, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n7387488333', 'Tres Ríos', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.81251, -82.96629, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n11363090271', 'Sabanero', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.81701, -82.96873, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154026087', 'Imas La Isla', 'locality', (select id from public.geo_places where osm_ref = 'r8476640'), 8.83057, -82.96013, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'r8477073', 'Aguabuena', 'district', (select id from public.geo_places where osm_ref = 'r6265593'), 8.73730, -82.94399, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437240326', 'Aguabuena', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.74810, -82.94301, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n4137458446', 'Cañas Gordas', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.74670, -82.92016, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n4137458447', 'Pilares', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.73869, -82.91197, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5785099493', 'Santa Cecilia', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.75594, -82.96384, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154235308', 'Campo 3', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.71918, -82.93139, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154314659', 'Quebrada Bonita', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.74312, -82.96152, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154328459', 'Pueblo Nuevo', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.73780, -82.95312, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5785092507', 'Copal', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.77916, -82.94979, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5785092508', 'San Francisco', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.76333, -82.94860, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5785092511', 'Valle Azul', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.76697, -82.93825, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5785092512', 'Concepción', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.77517, -82.96715, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5785099494', 'Santo Domingo', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.74414, -82.96940, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n6828934973', 'San Martín', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.75315, -82.93742, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n9281654229', 'Copabuena', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.74359, -82.94806, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154351727', 'Sabana Sur', 'locality', (select id from public.geo_places where osm_ref = 'r8477073'), 8.74112, -82.94739, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'r8477229', 'Sabalito', 'district', (select id from public.geo_places where osm_ref = 'r6265593'), 8.88286, -82.83143, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n2986976463', 'Sabalito', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.81555, -82.91119, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437271469', 'La Lucha', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.88663, -82.81324, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n3643242978', 'Mellizas', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.88741, -82.77519, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154282200', 'Los Ángeles', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.78766, -82.94223, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154282201', 'San Bosco', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.79882, -82.91678, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154380715', 'San Francisco', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.87149, -82.82443, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154404461', 'San Luis', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.87578, -82.86361, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154510040', 'San Antonio', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.77999, -82.91270, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154560621', 'Pueblo Nuevo', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.86007, -82.91312, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n13295752339', 'Río Sereno', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.81691, -82.86288, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437269461', 'Miraflores', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.83612, -82.91781, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437269546', 'La Unión', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.84045, -82.88343, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437270000', 'Valle Hermoso', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.84640, -82.89838, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437270136', 'San Miguel', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.85843, -82.87718, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437270255', 'Río Negro', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.87981, -82.85639, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5785169377', 'San Ramón', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.84991, -82.93490, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154282202', 'Plantel', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.80323, -82.93168, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154282203', 'Primavera', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.80553, -82.91521, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154510036', 'San Marcos', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.81208, -82.89235, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154510037', 'Brasilia', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.80167, -82.88429, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154510038', 'Trinidad', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.79673, -82.89677, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154510039', 'Santa Rosa', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.79309, -82.91022, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154510041', 'San Rafael', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.80799, -82.91221, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154530161', 'El Invu', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.81291, -82.91316, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154531257', 'La Ceiba', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.81462, -82.90342, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154531268', 'La Paz', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.81559, -82.90821, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154531269', 'Gonzalo Acuña', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.81340, -82.90762, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12154531274', 'El Pino', 'locality', (select id from public.geo_places where osm_ref = 'r8477229'), 8.81098, -82.90812, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'r8477332', 'Gutiérrez Braun', 'district', (select id from public.geo_places where osm_ref = 'r6265593'), 8.97025, -82.87751, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n3643290928', 'Fila Guinea', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.90226, -82.95322, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437266371', 'La Libertad', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.90928, -82.90492, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437267342', 'Siete Colinas', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.88081, -82.92203, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437270517', 'Flor del Roble', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.88772, -82.86876, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437270803', 'Alpha', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.88648, -82.88530, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437271773', 'Las Alturas de Cotón', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.93933, -82.83436, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n3643303775', 'Poma', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.90736, -82.92259, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n8812291411', 'Roble', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.90480, -82.88970, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n8812367779', 'Fila Pinar', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.88864, -82.95990, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12155875988', 'Río Marzo', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.89726, -82.87899, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12155888450', 'Sapo Triste', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.92592, -82.88270, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12155977634', 'La Administración', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.89704, -82.92048, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437267573', 'Barrantes', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.87248, -82.91516, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437268158', 'La Brisas', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.86485, -82.92682, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n5785245906', 'Bella Vista', 'locality', (select id from public.geo_places where osm_ref = 'r8477332'), 8.90541, -82.93943, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'r8477425', 'Pittier', 'district', (select id from public.geo_places where osm_ref = 'r6265593'), 8.99049, -82.96512, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n3643274328', 'Santa Elena', 'locality', (select id from public.geo_places where osm_ref = 'r8477425'), 8.93331, -82.94476, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437267249', 'Fila Naranjo', 'locality', (select id from public.geo_places where osm_ref = 'r8477425'), 8.91912, -82.95401, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n8356044576', 'Santa María de Pittier', 'locality', (select id from public.geo_places where osm_ref = 'r8477425'), 9.01579, -82.96502, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12155977633', 'Las Marías', 'locality', (select id from public.geo_places where osm_ref = 'r8477425'), 8.91730, -82.92899, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12156776695', 'Santa Fe', 'locality', (select id from public.geo_places where osm_ref = 'r8477425'), 8.93672, -82.98331, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12157883165', 'Sansi', 'locality', (select id from public.geo_places where osm_ref = 'r8477425'), 8.96231, -83.07031, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n12157896709', 'Palmira', 'locality', (select id from public.geo_places where osm_ref = 'r8477425'), 8.94053, -82.90346, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437264843', 'Aguacaliente', 'locality', (select id from public.geo_places where osm_ref = 'r8477425'), 8.95913, -82.93402, '{}'
on conflict (osm_ref) do nothing;
insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)
select 'n1437265066', 'Fila Tigre', 'locality', (select id from public.geo_places where osm_ref = 'r8477425'), 8.93786, -82.91730, '{}'
on conflict (osm_ref) do nothing;
