import { chromium } from "playwright";
const B = "http://localhost:3057";
const out = []; const ok = (n, c, extra="") => { out.push((c ? "PASS " : "FAIL ") + n + (c ? "" : " " + extra)); };
const br = await chromium.launch(); const pg = await br.newPage();
const errors = []; pg.on("pageerror", e => errors.push(String(e)));
await pg.goto(B + "/"); ok("signed-out redirects to login", pg.url().endsWith("/login"));
await pg.fill("input[name=email]", "e2e@example.test"); await pg.fill("input[name=password]", "E2e-pass-12345");
await pg.click("button:has-text(\"Sign in\")"); await pg.waitForURL(B + "/", { timeout: 20000 }).catch(()=>{});
ok("login works", pg.url() === B + "/", pg.url());
await pg.goto(B + "/applications"); ok("no workspace -> workspaces page", pg.url().endsWith("/subjects"), pg.url());
await pg.fill("input[name=name]", "E2E Cafe"); await pg.selectOption("select[name=kind]", "business"); await pg.click("button:has-text(\"Create\") >> nth=-1");
await pg.waitForSelector("text=E2E Cafe"); ok("workspace created", true);
await pg.goto(B + "/applications"); await pg.fill("input[name=company]", "Acme"); await pg.fill("input[name=title]", "Engineer"); await pg.click("button:has-text('Add')");
await pg.waitForSelector("text=Acme"); ok("application added", true);
await pg.selectOption("select[name=status]", "applied"); await pg.click("button:has-text('Move')"); await pg.waitForSelector("text=applied (1)"); ok("application moved to applied", true);
await pg.goto(B + "/posts"); await pg.fill("textarea[name=body]", "Hello world"); await pg.click("button:has-text('Save')"); await pg.waitForSelector("text=Hello world"); ok("post drafted", true);
await pg.goto(B + "/listings"); await pg.fill("input[name=title]", "Corner shop"); await pg.fill("input[name=price]", "250000"); await pg.click("button:has-text('Add')"); await pg.waitForSelector("text=Corner shop"); ok("listing added", true);
await pg.goto(B + "/team"); ok("team page renders", await pg.locator("h1").innerText().then(t => t.includes("E2E Cafe")));
await pg.fill("input[name=email]", "friend@example.test"); await pg.click("button:has-text('Invite')"); await pg.waitForSelector("text=friend@example.test"); ok("invite created", true);
await pg.goto(B + "/settings/email"); await pg.uncheck("input[name=marketing]"); await pg.click("button:has-text('Save')"); await pg.waitForTimeout(1500); await pg.reload(); ok("email pref persisted", !(await pg.isChecked("input[name=marketing]")));
await pg.goto(B + "/settings/privacy"); await pg.check("input[name=session_replay]"); await pg.click("button:has-text('Save')"); await pg.waitForTimeout(1500); await pg.reload(); ok("privacy consent persisted", await pg.isChecked("input[name=session_replay]"));
await pg.goto(B + "/admin/billing-plans"); await pg.fill("input[name=plan_key]", "Pro"); await pg.fill("input[name=tier]", "pro"); await pg.click("button:has-text('Save')"); await pg.waitForSelector("text=→"); ok("billing plan mapping saved (admin)", true);
ok("nav lists pack entries", (await pg.locator("nav a").count()) >= 8, String(await pg.locator("nav a").count()));
ok("no client-side exceptions", errors.length === 0, errors.join("; "));
console.log(out.join("\n")); await br.close();
