from gen import *
C = Col
packs = []

packs.append(Pack("image-generations", "igen", "Image generations",
  "Text-to-image jobs with the prompt, settings and results kept per person, charged by the database or by the platform that made them.",
  "Builders of an AI image app (any text-to-image model) who want the job record, credits and result storage done safely.",
  ["A generation per prompt: prompt, negative prompt, model, guidance, steps and number of outputs, owned by a workspace.",
   "Credits charged before the job and refunded exactly once if it fails; a replayed model callback changes nothing.",
   "A way to record images made elsewhere (for example by a Pickaxe agent) without charging core credits.",
   "Result images are private storage keys, never links that expire."],
  "item-tracker, subject-individual, image-transforms",
  "A child of item-tracker: every generation is an item with a 1:1 job row. Clients can read their jobs but cannot write them.",
  "Text-to-image generation jobs (the BuilderKit image_generations table; also the base for the Ghibli-style variant) as a child of item-tracker: prompt, settings and result keys per job, charged up front and refunded once on failure, or recorded from an outside generator.",
  [Entity("igen_generations", "igen", "image_generation", "job",
     [C("prompt","text",1,2000,sample="'a red fox in snow'"), C("negative_prompt","text",1,2000,req=False,sample="'blurry'"), C("model","text",1,100,sample="'flux-schnell'"),
      C("guidance","num",0,50,sample="7.5"), C("inference","int",1,200,sample="30"), C("no_of_outputs","int",1,8,sample="2")],
     outkeys=8, title="left(p_prompt, 200)", op="igen.generate", op_label="Generate an image", noun="image")],
  words="`image_generations` (id, user_id, prompt, negative_prompt, model, guidance, inference, no_of_outputs, image_urls[], prediction_id, error): `user_id` becomes the subject and `requested_by`; `image_urls[]` becomes `output_keys` (storage keys); `prediction_id` and `error` keep their meaning; guidance and step counts are typed numbers."))

packs.append(Pack("image-transforms", "itr", "Image transforms",
  "Upscale, enhance or restyle an image and keep the input, the result and the cost per person.",
  "Builders of an image-enhancer, upscaler or style-transfer app (including Ghibli-style) who want job tracking and credits done safely.",
  ["A job per image: transform type, the input image and the finished result, owned by a workspace.",
   "Credits charged before the job and refunded exactly once on failure; replays change nothing.",
   "A way to record transforms made elsewhere without charging core credits.",
   "Input and output are private storage keys, never inline images or expiring links."],
  "item-tracker, subject-individual, image-generations",
  "A child of item-tracker: every transform is an item with a 1:1 job row. Clients can read their jobs but cannot write them.",
  "Image upscale, enhance and style-transfer jobs (BuilderKit image_enhancer_upscaler and ghibli_generation tables) as a child of item-tracker: the input key, the result key and a free-text transform type, charged up front or recorded from an outside generator.",
  [Entity("itr_jobs", "itr", "image_transform", "job",
     [C("type","text",1,40,sample="'upscale'"), C("input_key","key",sample="'uploads/a/in.png'")],
     outkeys=1, title="p_type", op="itr.run", op_label="Transform an image", noun="Image transform")],
  words="`image_enhancer_upscaler` and `ghibli_generation` (id, user_id, type, input_image, output_image, prediction_id, error): both have the same shape, so one pack covers both with `type` as free text. `input_image` and `output_image` become storage keys (`input_key`, `output_keys`)."))

packs.append(Pack("music-generations", "mgn", "Music generations",
  "Text-to-music jobs with genre, mood and length kept per person, charged by the database or by the platform that made them.",
  "Builders of an AI music app who want the job record, credits and track storage done safely.",
  ["A track per prompt: prompt, genre, mood, duration and the finished audio, owned by a workspace.",
   "Credits charged before the job and refunded exactly once on failure; replays change nothing.",
   "A way to record tracks made elsewhere without charging core credits.",
   "Audio is a private storage key, never an expiring link."],
  "item-tracker, subject-individual, text-to-speech",
  "A child of item-tracker: every track is an item with a 1:1 job row. Clients can read their jobs but cannot write them.",
  "Text-to-music generation jobs (the BuilderKit music_generations table) as a child of item-tracker: prompt, genre, mood, duration and an audio key, charged up front or recorded from an outside generator.",
  [Entity("mgn_tracks", "mgn", "music_track", "job",
     [C("prompt","text",1,2000,sample="'calm piano'"), C("genre","text",1,60,sample="'ambient'"), C("mood","text",1,60,sample="'relaxed'"), C("duration","int",1,600,sample="30")],
     outkeys=1, title="left(p_genre || ' - ' || p_mood, 200)", op="mgn.generate", op_label="Generate a music track", noun="Music track")],
  words="`music_generations` (id, user_id, prompt, genre, mood, duration, music_url, prediction_id, error): `music_url` becomes `output_keys` (one storage key); duration is a bounded integer (seconds)."))

packs.append(Pack("voice-transcriptions", "vtr", "Voice transcriptions",
  "Audio in, transcript and summary out, kept per person and charged by the database or by the platform that did the work.",
  "Builders of a voice-to-text or meeting-notes app who want the job record, credits and transcript storage done safely.",
  ["A transcription per audio file: the audio key, the transcript and an optional summary, owned by a workspace.",
   "Credits charged before the job and refunded exactly once on failure; replays change nothing.",
   "A way to record transcripts made elsewhere without charging core credits.",
   "Audio is a private storage key, never an expiring link."],
  "item-tracker, subject-individual, youtube-content",
  "A child of item-tracker: every transcription is an item with a 1:1 job row. Clients can read their jobs but cannot write them.",
  "Voice-to-text jobs (the BuilderKit voice_transcriptions table) as a child of item-tracker: the audio key, transcript and summary, charged up front or recorded from an outside service.",
  [Entity("vtr_transcriptions", "vtr", "voice_transcription", "job",
     [C("audio_key","key",sample="'uploads/a/call.mp3'")],
     outs=[C("transcription","text",1,500000,req=False,sample="'hello world'"), C("summary","text",1,50000,req=False,sample="'a greeting'")],
     outkeys=None, title="null::text", op="vtr.transcribe", op_label="Transcribe audio", noun="Transcription")],
  words="`voice_transcriptions` (id, user_id, audio_url, transcription_id, transcription, summary, error): `audio_url` becomes `audio_key`; `transcription_id` becomes `prediction_id`."))

packs.append(Pack("qr-code-generations", "qrg", "QR code generations",
  "Artistic QR codes made from a prompt and a link, kept per person and charged by the database or by the platform that made them.",
  "Builders of an AI QR-code app who want the job record, credits and image storage done safely.",
  ["A QR code per request: prompt, target link and the finished image, owned by a workspace.",
   "Credits charged before the job and refunded exactly once on failure; replays change nothing.",
   "A way to record codes made elsewhere without charging core credits.",
   "The image is a private storage key, never an expiring link."],
  "item-tracker, subject-individual, image-generations",
  "A child of item-tracker: every QR code is an item with a 1:1 job row. Clients can read their jobs but cannot write them.",
  "AI QR-code generation jobs (the BuilderKit qr_code_generations table) as a child of item-tracker: prompt, target URL and an image key, charged up front or recorded from an outside generator.",
  [Entity("qrg_codes", "qrg", "qr_code", "job",
     [C("prompt","text",1,2000,sample="'a mountain village'"), C("url","text",1,2000,sample="'https://example.test/menu'")],
     outkeys=1, title="left(p_url, 200)", op="qrg.generate", op_label="Generate a QR code", noun="QR code")],
  words="`qr_code_generations` (id, user_id, prompt, url, image_url, error): `image_url` becomes `output_keys` (one storage key); there is no `prediction_id` in the original, the pack adds one for idempotency."))

packs.append(Pack("headshots", "hsh", "Headshots",
  "Train a personal model from a person's photos and generate professional headshots from it, with every step tracked and charged safely.",
  "Builders of an AI headshot app who want model training and generation records, credits and photo storage done safely.",
  ["A personal model per person: name, type, the training photos and its status, with an expiry when the provider deletes it.",
   "A headshot per prompt, generated from a finished model of the same workspace only.",
   "Credits charged before training and before each generation, refunded exactly once on failure; replays change nothing.",
   "Photos and results are private storage keys, never inline images or expiring links."],
  "item-tracker, subject-individual, image-generations",
  "Two children of item-tracker: models (kind headshot_model) and headshots (kind headshot). A headshot references a succeeded model of the same workspace through a composite key. Clients can read but cannot write.",
  "AI headshots as two children of item-tracker (BuilderKit headshot_models and headshot_generations): train a personal model from uploaded photos, then generate headshots from a finished model of the same workspace, charged up front or recorded from an outside generator.",
  [Entity("hsh_models", "hsh_model", "headshot_model", "job",
     [C("name","text",1,120,sample="'Work photos'"), C("model_type","text",1,40,sample="'person'"), C("input_keys","keys",1,30,sample="array['uploads/a/1.jpg','uploads/a/2.jpg']")],
     outs=[C("model_ref","text",1,200,req=False,sample="'provider-model-1'"), C("expires_at","ts",req=False,sample="now() + interval '30 days'")],
     outkeys=None, title="p_name", op="hsh.train", op_label="Train a headshot model", unique_subject=True, noun="Headshot model"),
   Entity("hsh_generations", "hsh_gen", "headshot", "job",
     [C("model_item","ref",ref="hsh_models",sample="m"), C("prompt","text",1,2000,sample="'studio portrait'"), C("negative_prompt","text",1,2000,req=False,sample="'blurry'")],
     outkeys=8, title="left(p_prompt, 200)", op="hsh.generate", op_label="Generate a headshot", noun="Headshot")],
  words="`headshot_models` (id, user_id, name, type, images[], model_id, status processing|finished, eta, trained_at, expires_at): `images[]` become `input_keys`; `model_id` becomes `model_ref`; status maps queued/processing/succeeded/failed; `trained_at` is `completed_at`; `eta` is not stored (derive it in the UI). `headshot_generations` (id, user_id, model_id, generation_id, prompt, negative_prompt, image_urls[]): `model_id` becomes `model_item` (a real foreign key to a finished model of the same workspace); `generation_id` becomes `prediction_id`."))

packs.append(Pack("text-to-speech", "tts", "Text to speech",
  "Turn text into spoken audio and keep each clip per person, recorded safely whether the app or an outside platform made it.",
  "Builders of a text-to-speech app who want the clip record, credits and audio storage done safely.",
  ["A clip per request: title, text, model, voice and the audio, owned by a workspace.",
   "Record a finished clip and, optionally, charge core credits in the same transaction; a replay returns the same clip.",
   "A way to record clips made elsewhere without charging core credits.",
   "Audio is a private storage key, never an expiring link."],
  "item-tracker, subject-individual, music-generations",
  "A child of item-tracker: every clip is an item with a 1:1 record row. Generation happens outside the database; a service-role function records the result once.",
  "Text-to-speech clips (the BuilderKit text_to_speech table) as a child of item-tracker: title, text, model, voice and an audio key, recorded once by the server with an optional core charge in the same transaction.",
  [Entity("tts_clips", "tts", "speech_clip", "record",
     [C("title","text",1,200,sample="'Welcome message'"), C("content","text",1,20000,sample="'Hello and welcome.'"), C("model","text",1,100,sample="'tts-1'"), C("voice","text",1,100,sample="'alloy'")],
     outs=[C("audio_key","key",sample="'out/a/clip.mp3'")],
     outkeys=None, title="p_title", op="tts.generate", op_label="Generate speech", noun="Speech clip")],
  words="`text_to_speech` (id, user_id, title, content, model, voice, audio_url): `audio_url` becomes `audio_key` (a storage key). Generation is synchronous in the original, so there is no job lifecycle: the server generates, then records."))

packs.append(Pack("content-writer", "cwr", "Content writer",
  "Keep every AI-written article per person with the topic, style and voice that produced it.",
  "Builders of an AI writing app who want the content record and credits done safely.",
  ["A piece per request: topic, style, voice, word limit and the finished text, owned by a workspace.",
   "Record a finished piece and, optionally, charge core credits in the same transaction; a replay returns the same piece.",
   "A way to record pieces written elsewhere without charging core credits."],
  "item-tracker, subject-individual, youtube-content",
  "A child of item-tracker: every piece is an item with a 1:1 record row. Generation happens outside the database; a service-role function records the result once.",
  "AI-written content pieces (the BuilderKit content_creations table) as a child of item-tracker: topic, style, voice, word limit and the text, recorded once by the server with an optional core charge in the same transaction.",
  [Entity("cwr_pieces", "cwr", "content_piece", "record",
     [C("topic","text",1,500,sample="'Winter skincare'"), C("style","text",1,60,sample="'friendly'"), C("voice","text",1,60,req=False,sample="'first person'"), C("word_limit","int",1,20000,req=False,sample="500")],
     outs=[C("results","text",1,100000,sample="'Some text.'")],
     outkeys=None, title="p_topic", op="cwr.generate", op_label="Write content", noun="Content piece")],
  words="`content_creations` (id, user_id, topic, style, voice, word_limit, results): `word_limit` is a bounded integer instead of a string."))

packs.append(Pack("youtube-content", "ytc", "YouTube content",
  "Turn a video's transcript into summaries and social content, kept per person with the source link.",
  "Builders of a video-to-content app who want the record and credits done safely.",
  ["A piece per video: link, title, language, transcript, summary and generated content, owned by a workspace.",
   "Record a finished piece and, optionally, charge core credits in the same transaction; a replay returns the same piece.",
   "A way to record pieces made elsewhere without charging core credits."],
  "item-tracker, subject-individual, chat-with-youtube",
  "A child of item-tracker: every piece is an item with a 1:1 record row. Transcription and generation happen outside the database; a service-role function records the result once.",
  "Video-to-content records (the BuilderKit youtube_content_generator table) as a child of item-tracker: link, title, language, transcript, summary and generated content, recorded once by the server with an optional core charge in the same transaction.",
  [Entity("ytc_pieces", "ytc", "youtube_content", "record",
     [C("url","text",1,2000,sample="'https://www.youtube.com/watch?v=abc'"), C("youtube_title","text",1,300,sample="'Intro video'"), C("language","text",1,40,req=False,sample="'en'")],
     outs=[C("transcription","text",1,500000,sample="'hello'"), C("summary","text",1,50000,req=False,sample="'a greeting'"), C("generated_content","jsonb",1,500000,req=False,sample="'{\"posts\":[\"a\"]}'::jsonb")],
     outkeys=None, title="p_youtube_title", op="ytc.generate", op_label="Generate content from a video", noun="Video content")],
  words="`youtube_content_generator` (id, user_id, url, youtube_title, language, transcription, summary, generated_content json): `generated_content` is size-bounded jsonb."))

if __name__ == "__main__":
    only = sys.argv[1:]
    for p in packs:
        if only and p.name not in only: continue
        write(p); print("wrote", p.name)
