// Prints SQL that loads one Costa Rican canton into geo_places from OpenStreetMap (Overpass): the province and canton, their districts, and the
// named places inside each district. Idempotent (osm_ref is unique). Usage:
//   node tools/load-canton.mjs <canton relation id> "<Province name>" > migrations/00N_seed_<canton>.sql
// Find the relation id with: [out:json];rel["boundary"="administrative"]["name"="Coto Brus"];out tags;  (admin_level 6 is a canton).
// Data is (c) OpenStreetMap contributors, ODbL. Attribution is required wherever the places are shown; see docs/README.md.
const [cantonId, provinceName] = process.argv.slice(2);
if (!cantonId || !provinceName) { console.error('usage: node tools/load-canton.mjs <canton relation id> "<Province>"'); process.exit(1); }
const MIRRORS = ['https://overpass.kumi.systems/api/interpreter', 'https://overpass-api.de/api/interpreter', 'https://overpass.private.coffee/api/interpreter'];
async function overpass(q) {
  for (let round = 0; round < 4; round++) {
    for (const u of MIRRORS) {
      try {
        const res = await fetch(u, { method: 'POST', body: new URLSearchParams({ data: q }), headers: { 'User-Agent': 'rapscalyon-places/0.1' }, signal: AbortSignal.timeout(150000) });
        const text = await res.text();
        if (text.startsWith('{')) return JSON.parse(text).elements;
      } catch { /* try the next mirror */ }
    }
    await new Promise((r) => setTimeout(r, 8000));
  }
  throw new Error('Overpass did not answer: ' + q.slice(0, 80));
}
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const KIND = { town: 'locality', city: 'locality', village: 'locality', hamlet: 'locality', neighbourhood: 'locality', suburb: 'locality', quarter: 'locality' };
const RANK = { town: 0, city: 0, village: 1, suburb: 2, hamlet: 3, quarter: 4, neighbourhood: 5 };
const area = (rel) => 3600000000 + Number(rel);

const [canton] = await overpass(`[out:json][timeout:60];rel(${Number(cantonId)});out tags center;`);
if (!canton || canton.tags.admin_level !== '6') throw new Error('that relation is not a canton (admin_level 6)');
const [province] = await overpass(`[out:json][timeout:60];rel["boundary"="administrative"]["admin_level"="4"]["name"=${JSON.stringify(provinceName)}];out tags center;`);
if (!province) throw new Error(`no province named ${provinceName}`);
const districts = await overpass(`[out:json][timeout:120];area(id:${area(cantonId)})->.c;rel(area.c)["boundary"="administrative"]["admin_level"="8"];out tags center;`);

const out = [`-- Generated by tools/load-canton.mjs from OpenStreetMap (ODbL): ${provinceName} > ${canton.tags.name}. Do not edit by hand.`];
const row = (ref, name, kind, parentRef, c, aliases = []) =>
  `insert into public.geo_places (osm_ref, name, kind, parent_id, lat, lon, aliases)\nselect ${q(ref)}, ${q(name)}, ${q(kind)}, ${parentRef ? `(select id from public.geo_places where osm_ref = ${q(parentRef)})` : 'null'}, ${c.lat.toFixed(5)}, ${c.lon.toFixed(5)}, ${aliases.length ? `array[${aliases.map(q).join(',')}]` : "'{}'"}\non conflict (osm_ref) do nothing;`;
out.push(row(`r${province.id}`, province.tags.name, 'province', null, province.center));
out.push(row(`r${canton.id}`, canton.tags.name, 'canton', `r${province.id}`, canton.center));
let places = 0;
for (const d of districts) {
  out.push(row(`r${d.id}`, d.tags.name, 'district', `r${canton.id}`, d.center));
  const nodes = await overpass(`[out:json][timeout:120];area(id:${area(d.id)})->.d;node(area.d)["place"~"^(town|village|hamlet|neighbourhood|suburb|quarter)$"]["name"];out;`);
  const kept = [];
  for (const n of nodes.sort((a, b) => RANK[a.tags.place] - RANK[b.tags.place])) {
    // the same name within 400 m is one place mapped twice (village and hamlet): keep the higher-ranked
    if (kept.some((k) => k.tags.name === n.tags.name && Math.hypot(k.lat - n.lat, k.lon - n.lon) < 0.004)) continue;
    kept.push(n);
  }
  for (const n of kept) { out.push(row(`n${n.id}`, n.tags.name, KIND[n.tags.place], `r${d.id}`, n)); places++; }
}
console.error(`${provinceName} > ${canton.tags.name}: ${districts.length} districts, ${places} places`);
console.log(out.join('\n'));
