-- Suite for headshots 0.1.0.
begin;
do $$
declare a uuid; b uuid; s uuid; d uuid; d2 uuid; m uuid;
begin
  a := t.make_user('hsh-a@example.test'); b := t.make_user('hsh-b@example.test');
  perform t.as_user(a);
  insert into public.subjects (owner_id, kind, name) values (a, 'individual', 'Me') returning id into s;
  -- hsh_models
  perform t.as_user(a);
  d := public.hsh_model_request(s, 'Work photos', 'person', array['uploads/a/1.jpg','uploads/a/2.jpg']);
  perform t.assert(t.rows('select 1 from public.it_items where id = ''' || d || ''' and kind = ''headshot_model''') = 1, 'request creates the base item');
  perform t.assert((select status = 'queued' and cost >= 0 from public.hsh_models where item_id = d), 'job starts queued with its cost');
  perform t.assert(t.rows('select 1 from public.credit_usage_log where idempotency_key = ''hsh_model:' || d || ''' and amount > 0') = 1, 'credits charged at request time');
  perform t.assert(t.denied('update public.hsh_models set status = ''succeeded'' where item_id = ''' || d || ''''), 'clients cannot update jobs');
  perform t.assert(t.denied('delete from public.hsh_models where item_id = ''' || d || ''''), 'clients cannot delete jobs');
  perform t.assert(t.denied('select public.hsh_model_mark_started(''' || d || ''', ''p1'')'), 'users cannot call executor functions');
  perform t.assert(t.denied('select public.hsh_model_fail(''' || d || ''', ''x'')'), 'users cannot fail jobs');
  perform t.as_service();
  perform t.assert(public.hsh_model_mark_started(d, 'pred-1'), 'start moves queued to processing');
  perform t.assert(not public.hsh_model_mark_started(d, 'pred-2'), 'a second start is a no-op');
  perform t.assert(public.hsh_model_complete(d, 'provider-model-1', now() + interval '30 days'), 'complete succeeds once');
  perform t.assert(not public.hsh_model_complete(d, 'provider-model-1', now() + interval '30 days'), 'a replayed completion changes nothing');
  perform t.assert(not public.hsh_model_fail(d, 'late failure'), 'a finished job cannot be failed or refunded');
  perform t.as_user(a);
  d2 := public.hsh_model_request(s, 'Work photos', 'person', array['uploads/a/1.jpg','uploads/a/2.jpg']);
  perform t.as_service();
  perform t.assert(public.hsh_model_fail(d2, 'model error'), 'fail marks the job failed');
  perform t.assert(not public.hsh_model_fail(d2, 'model error again'), 'a replayed failure is a no-op');
  perform t.assert(t.rows('select 1 from public.credit_usage_log where idempotency_key = ''hsh_model:' || d2 || ':refund''') = 1 or (select cost = 0 from public.hsh_models where item_id = d2), 'exactly one refund');
  perform t.as_user(a);
  perform t.assert(t.denied('select public.hsh_model_record(''' || s || ''', ''' || a || ''', ''ext-1'', ''Work photos'', ''person'', array[''uploads/a/1.jpg'',''uploads/a/2.jpg''], ''provider-model-1'', now() + interval ''30 days'')'), 'users cannot call hsh_model_record');
  perform t.as_service();
  d2 := public.hsh_model_record(s, a, 'ext-1', 'Work photos', 'person', array['uploads/a/1.jpg','uploads/a/2.jpg'], 'provider-model-1', now() + interval '30 days');
  perform t.assert(d2 = public.hsh_model_record(s, a, 'ext-1', 'Work photos', 'person', array['uploads/a/1.jpg','uploads/a/2.jpg'], 'provider-model-1', now() + interval '30 days'), 'a replayed record returns the same item');
  perform t.assert((select status = 'succeeded' and cost = 0 and charge_key is null from public.hsh_models where item_id = d2), 'recorded item is succeeded with no charge');
  perform t.assert(t.rows('select 1 from public.credit_usage_log where ref_id = ''' || d2 || '''') = 0, 'no core credits touched');
  perform t.assert(t.denied('select public.hsh_model_record(''' || s || ''', ''' || b || ''', ''ext-2'', ''Work photos'', ''person'', array[''uploads/a/1.jpg'',''uploads/a/2.jpg''], ''provider-model-1'', now() + interval ''30 days'')'), 'recording for a user without subject access is refused');
  m := d2;
  perform t.as_user(b);
  perform t.assert(t.rows('select 1 from public.hsh_models') = 0, 'other users see no jobs');
  perform t.assert(t.denied('select public.hsh_model_request(''' || s || ''', ''Work photos'', ''person'', array[''uploads/a/1.jpg'',''uploads/a/2.jpg''])'), 'cannot request into a foreign subject');
  perform t.as_anon();
  perform t.assert(t.denied('select 1 from public.hsh_models'), 'anon denied');
  perform t.assert(t.denied('select public.hsh_model_request(''' || s || ''', ''Work photos'', ''person'', array[''uploads/a/1.jpg'',''uploads/a/2.jpg''])'), 'anon cannot request');
  -- hsh_generations
  perform t.as_user(a);
  d := public.hsh_gen_request(s, m, 'studio portrait', 'blurry');
  perform t.assert(t.rows('select 1 from public.it_items where id = ''' || d || ''' and kind = ''headshot''') = 1, 'request creates the base item');
  perform t.assert((select status = 'queued' and cost >= 0 from public.hsh_generations where item_id = d), 'job starts queued with its cost');
  perform t.assert(t.rows('select 1 from public.credit_usage_log where idempotency_key = ''hsh_gen:' || d || ''' and amount > 0') = 1, 'credits charged at request time');
  perform t.assert(t.denied('update public.hsh_generations set status = ''succeeded'' where item_id = ''' || d || ''''), 'clients cannot update jobs');
  perform t.assert(t.denied('delete from public.hsh_generations where item_id = ''' || d || ''''), 'clients cannot delete jobs');
  perform t.assert(t.denied('select public.hsh_gen_mark_started(''' || d || ''', ''p1'')'), 'users cannot call executor functions');
  perform t.assert(t.denied('select public.hsh_gen_fail(''' || d || ''', ''x'')'), 'users cannot fail jobs');
  perform t.as_service();
  perform t.assert(public.hsh_gen_mark_started(d, 'pred-1'), 'start moves queued to processing');
  perform t.assert(not public.hsh_gen_mark_started(d, 'pred-2'), 'a second start is a no-op');
  perform t.assert(public.hsh_gen_complete(d, array['out/a/1.bin']), 'complete succeeds once');
  perform t.assert(not public.hsh_gen_complete(d, array['out/a/other.bin']), 'a replayed completion changes nothing');
  perform t.assert(not public.hsh_gen_fail(d, 'late failure'), 'a finished job cannot be failed or refunded');
  perform t.assert((select output_keys = array['out/a/1.bin'] from public.hsh_generations where item_id = d), 'result keys stored');
  perform t.as_user(a);
  d2 := public.hsh_gen_request(s, m, 'studio portrait', 'blurry');
  perform t.as_service();
  perform t.assert(public.hsh_gen_fail(d2, 'model error'), 'fail marks the job failed');
  perform t.assert(not public.hsh_gen_fail(d2, 'model error again'), 'a replayed failure is a no-op');
  perform t.assert(t.rows('select 1 from public.credit_usage_log where idempotency_key = ''hsh_gen:' || d2 || ':refund''') = 1 or (select cost = 0 from public.hsh_generations where item_id = d2), 'exactly one refund');
  perform t.as_user(a);
  perform t.assert(t.denied('select public.hsh_gen_record(''' || s || ''', ''' || a || ''', ''ext-1'', ''' || m || ''', ''studio portrait'', ''blurry'', array[''out/a/1.bin''])'), 'users cannot call hsh_gen_record');
  perform t.as_service();
  d2 := public.hsh_gen_record(s, a, 'ext-1', m, 'studio portrait', 'blurry', array['out/a/1.bin']);
  perform t.assert(d2 = public.hsh_gen_record(s, a, 'ext-1', m, 'studio portrait', 'blurry', array['out/a/1.bin']), 'a replayed record returns the same item');
  perform t.assert((select status = 'succeeded' and cost = 0 and charge_key is null from public.hsh_generations where item_id = d2), 'recorded item is succeeded with no charge');
  perform t.assert(t.rows('select 1 from public.credit_usage_log where ref_id = ''' || d2 || '''') = 0, 'no core credits touched');
  perform t.assert(t.denied('select public.hsh_gen_record(''' || s || ''', ''' || b || ''', ''ext-2'', ''' || m || ''', ''studio portrait'', ''blurry'', array[''out/a/1.bin''])'), 'recording for a user without subject access is refused');
  perform t.as_user(b);
  perform t.assert(t.rows('select 1 from public.hsh_generations') = 0, 'other users see no jobs');
  perform t.assert(t.denied('select public.hsh_gen_request(''' || s || ''', ''' || m || ''', ''studio portrait'', ''blurry'')'), 'cannot request into a foreign subject');
  perform t.as_anon();
  perform t.assert(t.denied('select 1 from public.hsh_generations'), 'anon denied');
  perform t.assert(t.denied('select public.hsh_gen_request(''' || s || ''', ''' || m || ''', ''studio portrait'', ''blurry'')'), 'anon cannot request');
  -- generations need a finished model of the same workspace
  perform t.as_user(a);
  d := public.hsh_model_request(s, 'Pending', 'person', array['uploads/a/1.jpg']);
  perform t.assert(t.denied('select public.hsh_gen_request(''' || s || ''', ''' || d || ''', ''portrait'', null)'), 'a model that is not finished cannot be used');
  perform t.as_user(b);
  insert into public.subjects (owner_id, kind, name) values (b, 'individual', 'Other') returning id into d2;
  perform t.assert(t.denied('select public.hsh_gen_request(''' || d2 || ''', ''' || m || ''', ''portrait'', null)'), 'a model of another workspace cannot be used');
end $$;
rollback;
