// GENERATED by tools/rapscalyon.py catalog. Do not edit.
export type CatalogEntry = { name: string; version: string; tier: string; license: string; description: string; title: string; tagline: string; sections: Record<string, string[]> };
export const catalog: CatalogEntry[] = [
 {
  "name": "billing-webhook",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Provider-agnostic subscription sync (FluentCart, WooCommerce, Stripe, anything that can POST a webhook): idempotent event application onto core profiles, plan-to-tier mapping, stale/out-of-order protection, and an unmatched-event health check.",
  "title": "Subscription billing sync",
  "tagline": "Connect WordPress and WooCommerce, FluentCart, Stripe or any webhook source to your app's plans.",
  "sections": {
   "Who it's for": [
    "Products that sell subscriptions through a store while the app itself runs on Supabase."
   ],
   "What you get": [
    "One endpoint that understands WooCommerce, WPSubscription and FluentCart events, plus a plain JSON format for anything else.",
    "Three authentication styles: WooCommerce HMAC signature, hex HMAC, or shared secret header.",
    "Plan mapping by exact key or by words in the product name, editable in an admin page.",
    "Idempotent, out-of-order safe, with a ledger of every event and an unmatched-customer health check."
   ],
   "Works well with": [
    "loops-email (welcome and win-back emails), posthog-analytics."
   ],
   "Under the hood": [
    "Tier changes only happen through one server function. Defaults match the PostGlider and JobsGlider policy: cancelled, expired, failed and refunded subscriptions return to free, configurable by an admin."
   ]
  }
 },
 {
  "name": "jobs-tracker",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Track job applications through a pipeline, with a per-application event log. A generic tracker, not an auto-apply engine.",
  "title": "Job application tracker",
  "tagline": "Keep every application, status and note in one pipeline, with an automatic history of each move.",
  "sections": {
   "Who it's for": [
    "Job seekers and career-services products that need a clean tracker rather than an auto-apply bot."
   ],
   "What you get": [
    "Saved, applied, interviewing, offer, rejected and withdrawn stages with company, role, link, location and pay range.",
    "A per-application event log written by the database, not the client.",
    "Plan-based cap on tracked applications; a health check for stale applications."
   ],
   "Works well with": [
    "subject-individual, loops-email, posthog-analytics."
   ],
   "Under the hood": [
    "Status history is recorded by a trigger, so it cannot be edited from the browser. Credits for AI resume tailoring are pre-wired through core pricing."
   ]
  }
 },
 {
  "name": "loops-email",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Transactional/lifecycle email through Loops: a durable outbox with at-most-once claiming, plus per-user email preferences. The Loops API key stays in the app environment.",
  "title": "Email with Loops",
  "tagline": "A reliable outbox for lifecycle and transactional email, with unsubscribes respected automatically.",
  "sections": {
   "Who it's for": [
    "Anyone using Loops who wants emails sent exactly once and users in control of what they receive."
   ],
   "What you get": [
    "`lp_enqueue` from any server code; a cron route drains the outbox into Loops with retries.",
    "Marketing versus product preferences per user, with a settings page included.",
    "Suppression of marketing events for opted-out users, enforced in the database."
   ],
   "Works well with": [
    "every pack that emits events: jobs-tracker, social-posts, billing-webhook."
   ],
   "Under the hood": [
    "Rows are claimed with `FOR UPDATE SKIP LOCKED`, sent with an idempotency key, and visible to their recipient only. The Loops key never touches the database."
   ]
  }
 },
 {
  "name": "posthog-analytics",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "PostHog product analytics with privacy controls: per-user analytics/session-replay consent that the app must check before sending any event. Keys stay in the app environment.",
  "title": "Product analytics with PostHog",
  "tagline": "Product analytics that checks consent first. Users decide what is measured.",
  "sections": {
   "Who it's for": [
    "Teams that want PostHog insight without a privacy surprise."
   ],
   "What you get": [
    "Per-user analytics and session-replay consent, with a privacy settings page.",
    "A server-side `ph_may_track` gate your code calls before sending events.",
    "Safe defaults: analytics on, session replay off, replay never without analytics consent."
   ],
   "Works well with": [
    "everything. Particularly useful with jobs-tracker and subject-individual."
   ],
   "Under the hood": [
    "Consent is private to its owner; the gate function is service-role only so users cannot probe each other."
   ]
  }
 },
 {
  "name": "real-estate-listings",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Property listings with photos and a publish workflow; AI description generation is a metered operation.",
  "title": "Real-estate listings",
  "tagline": "Property listings with photos, pricing and status, ready for an agency or an individual agent.",
  "sections": {
   "Who it's for": [
    "Agents, brokers and property managers who need to list and track properties without building a CRM first."
   ],
   "What you get": [
    "Listings with type, price in minor units, currency, beds, baths, area and structured address.",
    "Draft, active, pending, sold and withdrawn lifecycle.",
    "Photo records tied to private storage paths, shared automatically with your team."
   ],
   "Works well with": [
    "subject-business, team, social-posts, turnstile."
   ],
   "Under the hood": [
    "Prices are integers, not floats. Photos live in the private core `media` bucket under the subject's folder, so access rules match the listing's."
   ]
  }
 },
 {
  "name": "social-posts",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Draft, schedule and track social posts per subject. Publishing connectors live in the app layer and keep tokens in user_credentials.",
  "title": "Social post scheduler",
  "tagline": "Draft, schedule and track posts for any workspace. Bring your own publishing connectors.",
  "sections": {
   "Who it's for": [
    "Small businesses and creators who want a queue of posts that publishes itself."
   ],
   "What you get": [
    "Draft and scheduled states, scheduled-time validation, retry of failed posts.",
    "A safe claim function so two workers never publish the same post.",
    "Credit-priced AI operations for generating text and images."
   ],
   "Works well with": [
    "subject-business, team, real-estate-listings, loops-email."
   ],
   "Under the hood": [
    "Users cannot mark a post published; only the publisher (service role) moves posts through publishing states. Connector tokens belong in core `user_credentials`, never in this pack."
   ]
  }
 },
 {
  "name": "subject-business",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Subjects that are businesses or locations. Adds business details and a plan limit.",
  "title": "Business workspaces",
  "tagline": "A workspace for a company, shop or practice, with a public-facing business profile.",
  "sections": {
   "Who it's for": [
    "Apps that serve small businesses: local services, agencies, restaurants, clinics, real-estate offices."
   ],
   "What you get": [
    "Business workspaces with category, phone, website and structured address.",
    "Plan-based limit on how many businesses one account can run.",
    "Pairs with Team so a business can have staff, not just an owner."
   ],
   "Works well with": [
    "team, real-estate-listings, social-posts, loops-email."
   ],
   "Under the hood": [
    "Same secure-by-default rules as every pack. Can coexist with Individual workspaces in the same app."
   ]
  }
 },
 {
  "name": "subject-individual",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Subjects that are people (a persona, a profile, a job-seeker). Adds per-person details and a plan limit.",
  "title": "Individual workspaces",
  "tagline": "A personal workspace for every user: one person, one profile, their own private data.",
  "sections": {
   "Who it's for": [
    "Consumer and prosumer apps where each customer is a person: job seekers, creators, hobbyists, freelancers."
   ],
   "What you get": [
    "Every signup can create a personal workspace that all other packs attach to.",
    "Optional personal details (headline, location, links) kept private to the owner.",
    "A per-plan cap on how many personal workspaces one account may have."
   ],
   "Works well with": [
    "jobs-tracker, social-posts, posthog-analytics, billing-webhook."
   ],
   "Under the hood": [
    "Row-level security on every table, column-level grants, no anonymous access, MFA-aware policies. Removing the pack leaves your data model untouched."
   ]
  }
 },
 {
  "name": "team",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Share a subject with other users: invite by email, accept by token, remove members. Writes core subject_members through audited functions.",
  "title": "Team access",
  "tagline": "Invite colleagues to a workspace by email. They see what the workspace sees, nothing else.",
  "sections": {
   "Who it's for": [
    "Any app where one account needs to share work with staff, partners or clients."
   ],
   "What you get": [
    "Invite by email with admin, member or viewer roles; invitations expire after 7 days.",
    "One accept link; removing a member revokes access to every installed pack at once.",
    "Owner-only management, with every change going through audited server functions."
   ],
   "Works well with": [
    "subject-business, real-estate-listings, jobs-tracker, social-posts."
   ],
   "Under the hood": [
    "Invite tokens are bearer credentials only the owner can read. Members never gain table-level write access to membership data."
   ]
  }
 },
 {
  "name": "turnstile",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Cloudflare Turnstile bot protection: server-side verification audit log (failures, hashed IPs) and retention purge. The secret key stays in the app environment.",
  "title": "Bot protection with Turnstile",
  "tagline": "Verify Cloudflare Turnstile tokens on the server, log abuse safely, and slow repeat offenders.",
  "sections": {
   "Who it's for": [
    "Any public form: signup, contact, lead capture, comment, waitlist."
   ],
   "What you get": [
    "A ready `/api/turnstile/verify` route.",
    "Failure log keyed by an HMAC of the visitor's IP (never the raw address), readable by admins only.",
    "Automatic throttling after repeated failures and a nightly purge."
   ],
   "Works well with": [
    "every public entry point; especially signup and real-estate-listings enquiries."
   ],
   "Under the hood": [
    "Verification happens server-side only. Raw IPs are never stored, and retention defaults to 30 days."
   ]
  }
 }
];
