// GENERATED by tools/rapscalyon.py catalog. Do not edit.
export type CatalogEntry = { name: string; version: string; tier: string; license: string; description: string; requires: string[]; requires_core: string; contentHash: string; title: string; tagline: string; sections: Record<string, string[]> };
export const catalogVersion = "95dff65c2bce";
export const catalog: CatalogEntry[] = [
 {
  "name": "ai-chat",
  "version": "0.1.1",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "AI chat conversations as a child of item-tracker: a chat per provider and model with its messages in order, recorded by the server, with an optional core charge per reply in the same transaction. Covers the BuilderKit llamagpt, multillm_chatgpt, deepseek_chat and gemini_chat tables with one shape.",
  "requires": [
   "item-tracker"
  ],
  "requires_core": ">=0.1",
  "contentHash": "33b76f889c50a5cdd2890b1de527a26ecd80cc350860af48253993fd4e0ab2d3",
  "title": "AI chat",
  "tagline": "Keep every AI conversation per person, message by message, whichever model answered.",
  "sections": {
   "Who it's for": [
    "Builders of a chat app on any model provider (LLaMA, DeepSeek, Gemini, a multi-model switcher) who want conversation storage, ordering and optional credits done safely."
   ],
   "What you get": [
    "A chat per conversation: provider, model, title and a numbered message list, owned by a workspace.",
    "Messages are rows, not a JSON blob: ordered, countable, capped at 5,000 per chat.",
    "Optionally charge core credits per reply in the same transaction; a replay never charges twice.",
    "Nothing is charged by default: an outside platform's credits can stay the ledger."
   ],
   "Works well with": [
    "item-tracker, subject-individual, chat-with-file, chat-with-youtube."
   ],
   "Under the hood": [
    "A child of item-tracker: every chat is an item (kind chat) with a 1:1 chat row and many message rows. Clients can read; only the server writes, idempotently."
   ]
  }
 },
 {
  "name": "chat-with-file",
  "version": "0.1.1",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Chat with a document: the uploaded file's storage key and name attached 1:1 to an ai-chat conversation. Replaces the BuilderKit chat_with_file table.",
  "requires": [
   "item-tracker",
   "ai-chat"
  ],
  "requires_core": ">=0.1",
  "contentHash": "f4022dc20c6ea36c4ebfece489d7242cc1e36c02d8e1551956ce3aa98845f5c6",
  "title": "Chat with a file",
  "tagline": "Ask questions about an uploaded document and keep the conversation per person.",
  "sections": {
   "Who it's for": [
    "Builders of a chat-with-your-PDF app who want the document link and the conversation stored safely."
   ],
   "What you get": [
    "A document attached to a chat: its storage key and file name, owned by the same workspace as the chat.",
    "One document per chat; the conversation itself is an ai-chat conversation.",
    "The file is a private storage key, never an inline copy."
   ],
   "Works well with": [
    "ai-chat, item-tracker, subject-individual."
   ],
   "Under the hood": [
    "A 1:1 detail row on an ai-chat conversation. Clients can read; only the server writes, once."
   ]
  }
 },
 {
  "name": "chat-with-youtube",
  "version": "0.1.1",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Chat with a video: the link, title, style, tone, transcript and summary attached 1:1 to an ai-chat conversation, with an ingestion flag. Replaces the BuilderKit chat_with_youtube table.",
  "requires": [
   "item-tracker",
   "ai-chat"
  ],
  "requires_core": ">=0.1",
  "contentHash": "10b10f3ed2af946512db8ceec461cda6f844014f6e945420787d21cdef0ac8e5",
  "title": "Chat with a video",
  "tagline": "Ask questions about a YouTube video from its transcript and keep the conversation per person.",
  "sections": {
   "Who it's for": [
    "Builders of a chat-with-a-video app who want the transcript, summary and conversation stored safely."
   ],
   "What you get": [
    "A video attached to a chat: link, title, style, tone, transcript and summary, owned by the same workspace as the chat.",
    "An ingestion flag that flips once the transcript is indexed.",
    "One video per chat; the conversation itself is an ai-chat conversation."
   ],
   "Works well with": [
    "ai-chat, youtube-content, item-tracker."
   ],
   "Under the hood": [
    "A 1:1 detail row on an ai-chat conversation. Clients can read; only the server writes."
   ]
  }
 },
 {
  "name": "content-writer",
  "version": "0.1.1",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "AI-written content pieces (the BuilderKit content_creations table) as a child of item-tracker: topic, style, voice, word limit and the text, recorded once by the server with an optional core charge in the same transaction.",
  "requires": [
   "item-tracker"
  ],
  "requires_core": ">=0.1",
  "contentHash": "711b5981bbc5ac5b9206b3206f9d5faa1f9400778a1cf4b535c26a0a33216d59",
  "title": "Content writer",
  "tagline": "Keep every AI-written article per person with the topic, style and voice that produced it.",
  "sections": {
   "Who it's for": [
    "Builders of an AI writing app who want the content record and credits done safely."
   ],
   "What you get": [
    "A piece per request: topic, style, voice, word limit and the finished text, owned by a workspace.",
    "Record a finished piece and, optionally, charge core credits in the same transaction; a replay returns the same piece.",
    "A way to record pieces written elsewhere without charging core credits."
   ],
   "Works well with": [
    "item-tracker, subject-individual, youtube-content."
   ],
   "Under the hood": [
    "A child of item-tracker: every piece is an item with a 1:1 record row. Generation happens outside the database; a service-role function records the result once."
   ]
  }
 },
 {
  "name": "headshots",
  "version": "0.1.1",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "AI headshots as two children of item-tracker (BuilderKit headshot_models and headshot_generations): train a personal model from uploaded photos, then generate headshots from a finished model of the same workspace, charged up front or recorded from an outside generator.",
  "requires": [
   "item-tracker"
  ],
  "requires_core": ">=0.1",
  "contentHash": "daf48b8bf106d9f4e0b3ee4cd4acc83cb5e83b6c2e8ae48cd1a58b425faa3096",
  "title": "Headshots",
  "tagline": "Train a personal model from a person's photos and generate professional headshots from it, with every step tracked and charged safely.",
  "sections": {
   "Who it's for": [
    "Builders of an AI headshot app who want model training and generation records, credits and photo storage done safely."
   ],
   "What you get": [
    "A personal model per person: name, type, the training photos and its status, with an expiry when the provider deletes it.",
    "A headshot per prompt, generated from a finished model of the same workspace only.",
    "Credits charged before training and before each generation, refunded exactly once on failure; replays change nothing.",
    "Photos and results are private storage keys, never inline images or expiring links."
   ],
   "Works well with": [
    "item-tracker, subject-individual, image-generations."
   ],
   "Under the hood": [
    "Two children of item-tracker: models (kind headshot_model) and headshots (kind headshot). A headshot references a succeeded model of the same workspace through a composite key. Clients can read but cannot write."
   ]
  }
 },
 {
  "name": "image-generations",
  "version": "0.1.1",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Text-to-image generation jobs (the BuilderKit image_generations table; also the base for the Ghibli-style variant) as a child of item-tracker: prompt, settings and result keys per job, charged up front and refunded once on failure, or recorded from an outside generator.",
  "requires": [
   "item-tracker"
  ],
  "requires_core": ">=0.1",
  "contentHash": "57916e7ff3ee07549d44614b4efe516a82e5866b5ec3d7272cf6f7f4653d9c64",
  "title": "Image generations",
  "tagline": "Text-to-image jobs with the prompt, settings and results kept per person, charged by the database or by the platform that made them.",
  "sections": {
   "Who it's for": [
    "Builders of an AI image app (any text-to-image model) who want the job record, credits and result storage done safely."
   ],
   "What you get": [
    "A generation per prompt: prompt, negative prompt, model, guidance, steps and number of outputs, owned by a workspace.",
    "Credits charged before the job and refunded exactly once if it fails; a replayed model callback changes nothing.",
    "A way to record images made elsewhere (for example by a Pickaxe agent) without charging core credits.",
    "Result images are private storage keys, never links that expire."
   ],
   "Works well with": [
    "item-tracker, subject-individual, image-transforms."
   ],
   "Under the hood": [
    "A child of item-tracker: every generation is an item with a 1:1 job row. Clients can read their jobs but cannot write them."
   ]
  }
 },
 {
  "name": "image-transforms",
  "version": "0.1.1",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Image upscale, enhance and style-transfer jobs (BuilderKit image_enhancer_upscaler and ghibli_generation tables) as a child of item-tracker: the input key, the result key and a free-text transform type, charged up front or recorded from an outside generator.",
  "requires": [
   "item-tracker"
  ],
  "requires_core": ">=0.1",
  "contentHash": "cd7329f7e7993a0e13d7af1c9ee235fb205cf971cbd4ee48ade28ae3c509fd4f",
  "title": "Image transforms",
  "tagline": "Upscale, enhance or restyle an image and keep the input, the result and the cost per person.",
  "sections": {
   "Who it's for": [
    "Builders of an image-enhancer, upscaler or style-transfer app (including Ghibli-style) who want job tracking and credits done safely."
   ],
   "What you get": [
    "A job per image: transform type, the input image and the finished result, owned by a workspace.",
    "Credits charged before the job and refunded exactly once on failure; replays change nothing.",
    "A way to record transforms made elsewhere without charging core credits.",
    "Input and output are private storage keys, never inline images or expiring links."
   ],
   "Works well with": [
    "item-tracker, subject-individual, image-generations."
   ],
   "Under the hood": [
    "A child of item-tracker: every transform is an item with a 1:1 job row. Clients can read their jobs but cannot write them."
   ]
  }
 },
 {
  "name": "interior-designs",
  "version": "0.2.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "AI room redesigns as a child of item-tracker: prompt, room type, theme and a reference photo become either a generation job charged up front in core credits and refunded once on failure, or a design recorded from an outside generator such as a Pickaxe agent, whose own credits are then the only ledger and which charges no core credits. Written from the BKIDA schema and behaviour, with no BuilderKit code.",
  "requires": [
   "item-tracker"
  ],
  "requires_core": ">=0.1",
  "contentHash": "c8a06ee21fc7d68e766080aba6b06ea578a3661460f0a17fc62b0d26a5c8b910",
  "title": "Interior designs",
  "tagline": "AI room redesigns, owned by the person who made them, saved safely and charged either by the database or by the outside platform that made them.",
  "sections": {
   "Who it's for": [
    "Builders of an interior-design app, or any room-makeover product, who want the generation record, credits and result storage done safely instead of rebuilt from a boilerplate."
   ],
   "What you get": [
    "A design per room: prompt, room type, theme, reference photo and the finished images, owned by the person's Space (a home or a business).",
    "Two ways to pay: the app's own generator can charge core credits before generation and refund exactly once on failure; or, when an outside platform such as Pickaxe makes the image, that platform's credits are the only ledger and the app charges nothing.",
    "A way to record designs made outside the app, for example by a Pickaxe agent, never charging core credits for them.",
    "Image locations are stored as private storage keys, never as links that expire."
   ],
   "Works well with": [
    "item-tracker, subject-individual, interior-design-bid-process."
   ],
   "In your customers' words": [
    "Customers see Spaces (a home or a business) and Designs; the technical terms never reach them."
   ],
   "Under the hood": [
    "A child of item-tracker: every design is an item of kind interior_design with a 1:1 row for the generation job. Clients can read their designs but cannot write the job; only the server-side functions move it forward."
   ]
  }
 },
 {
  "name": "invoice-refunds",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Customers, invoices, line items and refunds with the money rules enforced by the database: totals, balances, and refunds only against paid invoices, never beyond what was paid. Ships the same rules in GenAI-Logic form.",
  "requires": [],
  "requires_core": ">=0.1",
  "contentHash": "5d33aae6be2648a3071790567d50d8d849c56addb0e2176fcdfca773ccc4e8b8",
  "title": "Invoices and refunds",
  "tagline": "Invoices where the rules are the database's job: refunds only against paid invoices, never more than was paid.",
  "sections": {
   "Who it's for": [
    "Freelancers and small businesses who invoice customers and refund them, and who want the money rules guaranteed instead of re-implemented in every screen."
   ],
   "What you get": [
    "Customers, invoices and line items with totals and balances computed for you.",
    "Refund requests that must reference a paid invoice, cannot exceed what remains, and are approved only by the workspace owner.",
    "An outbox event for every approved refund, ready for an email worker.",
    "The same rules written in GenAI-Logic's declarative form, as a starting point for a rules-engine backend."
   ],
   "Works well with": [
    "subject-individual, subject-business, loops-email."
   ],
   "Under the hood": [
    "Triggers write every derived value; clients cannot. Role-switched SQL tests try to break each rule."
   ]
  }
 },
 {
  "name": "item-search",
  "version": "0.3.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Saved search profiles, candidate items proposed by an external matcher, and a review-then-dispatch queue for a worker. Ships the plumbing and the security model, not the matching intelligence.",
  "requires": [
   "item-tracker"
  ],
  "requires_core": ">=0.1",
  "contentHash": "8bab1359be294da6afbf35ef2063f7b2242342a9a968848d006eb9bc8010ce7a",
  "title": "Item search",
  "tagline": "Saved searches, a review inbox and a safe worker queue, with your matcher plugged in from outside.",
  "sections": {
   "Who it's for": [
    "Products that find things for people (jobs, listings, leads) and want the user to approve before anything is acted on in their name."
   ],
   "What you get": [
    "Saved search profiles per workspace with flexible criteria and exclusions, capped by plan.",
    "A candidate inbox: accept to create a tracked item, or dismiss, with duplicate-safe delivery from any matcher.",
    "A review-then-dispatch queue: edit overrides, approve with an optional delay, or cancel; workers claim each job exactly once.",
    "A poll-based event outbox so matchers and workers know when to run. No webhooks or stored secrets inside the database."
   ],
   "Works well with": [
    "item-tracker, loops-email (commercial child: jobs-search)."
   ],
   "Under the hood": [
    "Every user action is a function that checks the caller, the workspace and the MFA gate. The queue contract is three service-role functions, and the pack contains no matching or submission logic."
   ],
   "Matching recipe": [
    "The pack contains no matching, but ships a recipe for child packs that rank by deal quality and fit (`docs/MATCHING.md`): preferences are scored, hard filters are real exclusions, fit is a weighted 0 to 100 score, value is the gap to a comparables-based fair value with a confidence, and delivery is gate-then-blend with fixed scaling. It also says how to value without self-reference and how to test without tuning on the answer. The six worker stages (fetch, normalize, extract, value, score, deliver) have a typed contract in `docs/WORKER.md`, so a Builder can target each stage on its own."
   ]
  }
 },
 {
  "name": "item-tracker",
  "version": "0.1.1",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "The base class for anything a subject tracks: a typed item (job, listing, lead, ...) with notes, a link and an append-only event log. Child packs add typed columns for one kind of item.",
  "requires": [],
  "requires_core": ">=0.1",
  "contentHash": "39724a3cab96754594c1fe2f02016c98ae4cdfb50ad0d22bf419783986e821b6",
  "title": "Item tracker",
  "tagline": "One tracked-thing model for any vertical, with an event log the browser cannot rewrite.",
  "sections": {
   "Who it's for": [
    "Builders who need to track jobs, listings, leads or anything similar and want one proven foundation instead of a new table design each time."
   ],
   "What you get": [
    "Typed items with title, link, source and notes, owned by a workspace subject.",
    "An append-only event log; status history is written by the database, not the client.",
    "A plan cap on items per subject, archive instead of delete, and row-level security with the MFA gate on every table."
   ],
   "Works well with": [
    "subject-individual, subject-business, item-search, social-posts."
   ],
   "Under the hood": [
    "Class-table inheritance: child packs add a 1:1 table keyed on the item, so each kind keeps real columns and constraints while access rules live in one place."
   ]
  }
 },
 {
  "name": "loops-email",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Transactional/lifecycle email through Loops: a durable outbox with at-most-once claiming, plus per-user email preferences. The Loops API key stays in the app environment.",
  "requires": [],
  "requires_core": ">=0.1",
  "contentHash": "00fc3b75e296ea9ed7ecc3f6cb41ddb081fc2fc092189ce54bd603c74b5bae2a",
  "title": "Email with Loops",
  "tagline": "A reliable outbox for lifecycle and transactional email, with unsubscribes respected automatically.",
  "sections": {
   "Who it's for": [
    "Anyone using Loops who wants emails sent exactly once and users in control of what they receive."
   ],
   "What you get": [
    "`lp_enqueue` from any server code; a cron route drains the outbox into Loops with retries.",
    "Marketing versus product preferences per user, with a settings page included.",
    "Suppression of marketing events for opted-out users, enforced in the database."
   ],
   "Works well with": [
    "every pack that emits events: item-tracker, social-posts."
   ],
   "Under the hood": [
    "Rows are claimed with `FOR UPDATE SKIP LOCKED`, sent with an idempotency key, and visible to their recipient only. The Loops key never touches the database."
   ]
  }
 },
 {
  "name": "music-generations",
  "version": "0.1.1",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Text-to-music generation jobs (the BuilderKit music_generations table) as a child of item-tracker: prompt, genre, mood, duration and an audio key, charged up front or recorded from an outside generator.",
  "requires": [
   "item-tracker"
  ],
  "requires_core": ">=0.1",
  "contentHash": "173815b075a509328978a54fd18fa8be7085f33fa46b99c648cfe31fa9ef52c1",
  "title": "Music generations",
  "tagline": "Text-to-music jobs with genre, mood and length kept per person, charged by the database or by the platform that made them.",
  "sections": {
   "Who it's for": [
    "Builders of an AI music app who want the job record, credits and track storage done safely."
   ],
   "What you get": [
    "A track per prompt: prompt, genre, mood, duration and the finished audio, owned by a workspace.",
    "Credits charged before the job and refunded exactly once on failure; replays change nothing.",
    "A way to record tracks made elsewhere without charging core credits.",
    "Audio is a private storage key, never an expiring link."
   ],
   "Works well with": [
    "item-tracker, subject-individual, text-to-speech."
   ],
   "Under the hood": [
    "A child of item-tracker: every track is an item with a 1:1 job row. Clients can read their jobs but cannot write them."
   ]
  }
 },
 {
  "name": "places",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Places for Costa Rica: provinces, cantons, districts and named localities with coordinates (OpenStreetMap), accent-tolerant name lookup, nearest place to a point, and distance in kilometres. Other packs use it to turn a place name or a phone's location into coordinates.",
  "requires": [],
  "requires_core": ">=0.1",
  "contentHash": "3dd686537ac93ea51c823bd93603cc188997247270a6b88f02de4e3bacb6b7cb",
  "title": "Places",
  "tagline": "A place directory for Costa Rica (Provincia, Cant\u00f3n, Distrito, town) with distance and \"where is this?\" lookups built in.",
  "sections": {
   "Who it's for": [
    "Builders of listing, delivery or matching products who need to rank by distance, let people pick where they live, or turn \"placed in Sabalito\" into coordinates."
   ],
   "What you get": [
    "Provincia, Cant\u00f3n, Distrito and town records from OpenStreetMap, ready to load for any canton.",
    "Typo- and accent-tolerant search, nearest-place lookup from a GPS point, and the place named inside free text.",
    "Straight-line distance in kilometres, with no map service and no per-lookup cost."
   ],
   "Works well with": [
    "items-matching-ranking, real-estate-listings, item-search."
   ],
   "Under the hood": [
    "Plain tables and SQL functions: a trigram index for fuzzy names, haversine for distance. Read-only reference data behind row-level security and the MFA gate. Place data \u00a9 OpenStreetMap contributors (ODbL)."
   ]
  }
 },
 {
  "name": "posthog-analytics",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "PostHog product analytics with privacy controls: per-user analytics/session-replay consent that the app must check before sending any event. Keys stay in the app environment.",
  "requires": [],
  "requires_core": ">=0.1",
  "contentHash": "fafc40f8453a38811ceb1e7e12009bbd6a7634e3a7f3f9d14eee5cdc9482886c",
  "title": "Product analytics with PostHog",
  "tagline": "Product analytics that checks consent first. Users decide what is measured.",
  "sections": {
   "Who it's for": [
    "Teams that want PostHog insight without a privacy surprise."
   ],
   "What you get": [
    "Per-user analytics and session-replay consent, with a privacy settings page.",
    "A server-side `ph_may_track` gate your code calls before sending events.",
    "Safe defaults: analytics on, session replay off, replay never without analytics consent."
   ],
   "Works well with": [
    "everything. Particularly useful with item-tracker and subject-individual."
   ],
   "Under the hood": [
    "Consent is private to its owner; the gate function is service-role only so users cannot probe each other."
   ]
  }
 },
 {
  "name": "qr-code-generations",
  "version": "0.1.1",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "AI QR-code generation jobs (the BuilderKit qr_code_generations table) as a child of item-tracker: prompt, target URL and an image key, charged up front or recorded from an outside generator.",
  "requires": [
   "item-tracker"
  ],
  "requires_core": ">=0.1",
  "contentHash": "111307281ce25e983727621d3cc7003d055a85882de8b469a82cddae883224c0",
  "title": "QR code generations",
  "tagline": "Artistic QR codes made from a prompt and a link, kept per person and charged by the database or by the platform that made them.",
  "sections": {
   "Who it's for": [
    "Builders of an AI QR-code app who want the job record, credits and image storage done safely."
   ],
   "What you get": [
    "A QR code per request: prompt, target link and the finished image, owned by a workspace.",
    "Credits charged before the job and refunded exactly once on failure; replays change nothing.",
    "A way to record codes made elsewhere without charging core credits.",
    "The image is a private storage key, never an expiring link."
   ],
   "Works well with": [
    "item-tracker, subject-individual, image-generations."
   ],
   "Under the hood": [
    "A child of item-tracker: every QR code is an item with a 1:1 job row. Clients can read their jobs but cannot write them."
   ]
  }
 },
 {
  "name": "real-estate-listings",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Property listings with photos and a publish workflow; AI description generation is a metered operation.",
  "requires": [],
  "requires_core": ">=0.1",
  "contentHash": "7183477bac65321f7d0ac4db6405eca513b803fc61b87b8fb67501b21723afcd",
  "title": "Real-estate listings",
  "tagline": "Property listings with photos, pricing and status, ready for an agency or an individual agent.",
  "sections": {
   "Who it's for": [
    "Agents, brokers and property managers who need to list and track properties without building a CRM first."
   ],
   "What you get": [
    "Listings with type, price in minor units, currency, beds, baths, area and structured address.",
    "Draft, active, pending, sold and withdrawn lifecycle.",
    "Photo records tied to private storage paths, shared automatically with your team."
   ],
   "Works well with": [
    "subject-business, team, social-posts, turnstile."
   ],
   "Under the hood": [
    "Prices are integers, not floats. Photos live in the private core `media` bucket under the subject's folder, so access rules match the listing's."
   ]
  }
 },
 {
  "name": "social-posts",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Draft, schedule and track social posts per subject. Publishing connectors live in the app layer and keep tokens in user_credentials.",
  "requires": [],
  "requires_core": ">=0.1",
  "contentHash": "f4194fbddcb9161adf647655161f9813610333232c894b3aed9ca701ce2a9d7c",
  "title": "Social post scheduler",
  "tagline": "Draft, schedule and track posts for any workspace. Bring your own publishing connectors.",
  "sections": {
   "Who it's for": [
    "Small businesses and creators who want a queue of posts that publishes itself."
   ],
   "What you get": [
    "Draft and scheduled states, scheduled-time validation, retry of failed posts.",
    "A safe claim function so two workers never publish the same post.",
    "Credit-priced AI operations for generating text and images."
   ],
   "Works well with": [
    "subject-business, team, real-estate-listings, loops-email."
   ],
   "Under the hood": [
    "Users cannot mark a post published; only the publisher (service role) moves posts through publishing states. Connector tokens belong in core `user_credentials`, never in this pack."
   ]
  }
 },
 {
  "name": "subject-business",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Subjects that are businesses or locations. Adds business details and a plan limit.",
  "requires": [],
  "requires_core": ">=0.1",
  "contentHash": "930a1f4419f13011791f159051b7542086f92109e9560c7ef816efc404a2f143",
  "title": "Business workspaces",
  "tagline": "A workspace for a company, shop or practice, with a public-facing business profile.",
  "sections": {
   "Who it's for": [
    "Apps that serve small businesses: local services, agencies, restaurants, clinics, real-estate offices."
   ],
   "What you get": [
    "Business workspaces with category, phone, website and structured address.",
    "Plan-based limit on how many businesses one account can run.",
    "Pairs with Team so a business can have staff, not just an owner."
   ],
   "Works well with": [
    "team, real-estate-listings, social-posts, loops-email."
   ],
   "Under the hood": [
    "Same secure-by-default rules as every pack. Can coexist with Individual workspaces in the same app."
   ]
  }
 },
 {
  "name": "subject-individual",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Subjects that are people (a persona, a profile, a job-seeker). Adds per-person details and a plan limit.",
  "requires": [],
  "requires_core": ">=0.1",
  "contentHash": "72755b8fd86f85518777cc3e853c3d8b051a89d164e808273ced18d7ccce1a13",
  "title": "Individual workspaces",
  "tagline": "A personal workspace for every user: one person, one profile, their own private data.",
  "sections": {
   "Who it's for": [
    "Consumer and prosumer apps where each customer is a person: job seekers, creators, hobbyists, freelancers."
   ],
   "What you get": [
    "Every signup can create a personal workspace that all other packs attach to.",
    "Optional personal details (headline, location, links) kept private to the owner.",
    "A per-plan cap on how many personal workspaces one account may have."
   ],
   "Works well with": [
    "item-tracker, social-posts, posthog-analytics."
   ],
   "Under the hood": [
    "Row-level security on every table, column-level grants, no anonymous access, MFA-aware policies. Removing the pack leaves your data model untouched."
   ]
  }
 },
 {
  "name": "team",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Share a subject with other users: invite by email, accept by token, remove members. Writes core subject_members through audited functions.",
  "requires": [],
  "requires_core": ">=0.1",
  "contentHash": "15692054c1aaf7b2c80401feb88354bbafcbd58424418916a1e5cf5e56359029",
  "title": "Team access",
  "tagline": "Invite colleagues to a workspace by email. They see what the workspace sees, nothing else.",
  "sections": {
   "Who it's for": [
    "Any app where one account needs to share work with staff, partners or clients."
   ],
   "What you get": [
    "Invite by email with admin, member or viewer roles; invitations expire after 7 days.",
    "One accept link; removing a member revokes access to every installed pack at once.",
    "Owner-only management, with every change going through audited server functions."
   ],
   "Works well with": [
    "subject-business, real-estate-listings, item-tracker, social-posts."
   ],
   "Under the hood": [
    "Invite tokens are bearer credentials only the owner can read. Members never gain table-level write access to membership data."
   ]
  }
 },
 {
  "name": "text-to-speech",
  "version": "0.1.1",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Text-to-speech clips (the BuilderKit text_to_speech table) as a child of item-tracker: title, text, model, voice and an audio key, recorded once by the server with an optional core charge in the same transaction.",
  "requires": [
   "item-tracker"
  ],
  "requires_core": ">=0.1",
  "contentHash": "4a7adb2e6da8a983bf4915c80b0e58c34d2e9fd5793681428f21c357a299c073",
  "title": "Text to speech",
  "tagline": "Turn text into spoken audio and keep each clip per person, recorded safely whether the app or an outside platform made it.",
  "sections": {
   "Who it's for": [
    "Builders of a text-to-speech app who want the clip record, credits and audio storage done safely."
   ],
   "What you get": [
    "A clip per request: title, text, model, voice and the audio, owned by a workspace.",
    "Record a finished clip and, optionally, charge core credits in the same transaction; a replay returns the same clip.",
    "A way to record clips made elsewhere without charging core credits.",
    "Audio is a private storage key, never an expiring link."
   ],
   "Works well with": [
    "item-tracker, subject-individual, music-generations."
   ],
   "Under the hood": [
    "A child of item-tracker: every clip is an item with a 1:1 record row. Generation happens outside the database; a service-role function records the result once."
   ]
  }
 },
 {
  "name": "turnstile",
  "version": "0.1.0",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Cloudflare Turnstile bot protection: server-side verification audit log (failures, hashed IPs) and retention purge. The secret key stays in the app environment.",
  "requires": [],
  "requires_core": ">=0.1",
  "contentHash": "715781db1b69e64f239ea9aa7e9b471d81c7a614e717ea30815263728f7b1245",
  "title": "Bot protection with Turnstile",
  "tagline": "Verify Cloudflare Turnstile tokens on the server, log abuse safely, and slow repeat offenders.",
  "sections": {
   "Who it's for": [
    "Any public form: signup, contact, lead capture, comment, waitlist."
   ],
   "What you get": [
    "A ready `/api/turnstile/verify` route.",
    "Failure log keyed by an HMAC of the visitor's IP (never the raw address), readable by admins only.",
    "Automatic throttling after repeated failures and a nightly purge."
   ],
   "Works well with": [
    "every public entry point; especially signup and real-estate-listings enquiries."
   ],
   "Under the hood": [
    "Verification happens server-side only. Raw IPs are never stored, and retention defaults to 30 days."
   ]
  }
 },
 {
  "name": "voice-transcriptions",
  "version": "0.1.1",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Voice-to-text jobs (the BuilderKit voice_transcriptions table) as a child of item-tracker: the audio key, transcript and summary, charged up front or recorded from an outside service.",
  "requires": [
   "item-tracker"
  ],
  "requires_core": ">=0.1",
  "contentHash": "85e214a75da61b0c26ff03ccc1a5960a6d72910d26c1cc51311beec48f2107b7",
  "title": "Voice transcriptions",
  "tagline": "Audio in, transcript and summary out, kept per person and charged by the database or by the platform that did the work.",
  "sections": {
   "Who it's for": [
    "Builders of a voice-to-text or meeting-notes app who want the job record, credits and transcript storage done safely."
   ],
   "What you get": [
    "A transcription per audio file: the audio key, the transcript and an optional summary, owned by a workspace.",
    "Credits charged before the job and refunded exactly once on failure; replays change nothing.",
    "A way to record transcripts made elsewhere without charging core credits.",
    "Audio is a private storage key, never an expiring link."
   ],
   "Works well with": [
    "item-tracker, subject-individual, youtube-content."
   ],
   "Under the hood": [
    "A child of item-tracker: every transcription is an item with a 1:1 job row. Clients can read their jobs but cannot write them."
   ]
  }
 },
 {
  "name": "youtube-content",
  "version": "0.1.1",
  "tier": "official",
  "license": "AGPL-3.0-or-later",
  "description": "Video-to-content records (the BuilderKit youtube_content_generator table) as a child of item-tracker: link, title, language, transcript, summary and generated content, recorded once by the server with an optional core charge in the same transaction.",
  "requires": [
   "item-tracker"
  ],
  "requires_core": ">=0.1",
  "contentHash": "1da63634394c6bfee468b569c100b8a95089267b21c4d2e1bb542fe4c368f4e0",
  "title": "YouTube content",
  "tagline": "Turn a video's transcript into summaries and social content, kept per person with the source link.",
  "sections": {
   "Who it's for": [
    "Builders of a video-to-content app who want the record and credits done safely."
   ],
   "What you get": [
    "A piece per video: link, title, language, transcript, summary and generated content, owned by a workspace.",
    "Record a finished piece and, optionally, charge core credits in the same transaction; a replay returns the same piece.",
    "A way to record pieces made elsewhere without charging core credits."
   ],
   "Works well with": [
    "item-tracker, subject-individual, chat-with-youtube."
   ],
   "Under the hood": [
    "A child of item-tracker: every piece is an item with a 1:1 record row. Transcription and generation happen outside the database; a service-role function records the result once."
   ]
  }
 }
];
