// GENERATED by tools/rapscalyon.py (pack add --app app). Do not edit.
export const packRegistry = { nav: [], limits: {}, health: [], events: [], operations: [] } as { nav: { label: string; href: string; icon: string; group: string; pack: string }[]; limits: Record<string, number>; health: { id: string; pack: string }[]; events: unknown[]; operations: unknown[] };
