// GENERATED by tools/rapscalyon.py. Do not edit.
export const packRegistry = {
  "nav": [
    {
      "label": "Billing plans",
      "href": "/admin/billing-plans",
      "icon": "CreditCard",
      "group": "admin",
      "pack": "billing-webhook"
    },
    {
      "label": "Applications",
      "href": "/applications",
      "icon": "Briefcase",
      "group": "main",
      "pack": "jobs-tracker"
    },
    {
      "label": "Email preferences",
      "href": "/settings/email",
      "icon": "Mail",
      "group": "settings",
      "pack": "loops-email"
    },
    {
      "label": "Privacy",
      "href": "/settings/privacy",
      "icon": "Shield",
      "group": "settings",
      "pack": "posthog-analytics"
    },
    {
      "label": "Listings",
      "href": "/listings",
      "icon": "Home",
      "group": "main",
      "pack": "real-estate-listings"
    },
    {
      "label": "Posts",
      "href": "/posts",
      "icon": "Send",
      "group": "main",
      "pack": "social-posts"
    },
    {
      "label": "People",
      "href": "/people",
      "icon": "Users",
      "group": "main",
      "pack": "subject-individual"
    },
    {
      "label": "Team",
      "href": "/team",
      "icon": "UserPlus",
      "group": "account",
      "pack": "team"
    }
  ],
  "limits": {
    "jb_max_applications": 100,
    "lp_max_pending": 500,
    "rel_max_active_listings": 10,
    "sp_max_scheduled": 30,
    "ind_max_subjects": 1,
    "team_max_members": 3
  },
  "health": [
    {
      "id": "bw_unmatched_events",
      "pack": "billing-webhook"
    },
    {
      "id": "jb_stale_applications",
      "pack": "jobs-tracker"
    },
    {
      "id": "lp_stuck_outbox",
      "pack": "loops-email"
    },
    {
      "id": "rel_stale_listings",
      "pack": "real-estate-listings"
    }
  ],
  "events": [],
  "operations": [
    {
      "name": "jb.tailor_resume",
      "label": "Tailor resume to a posting",
      "pack": "jobs-tracker"
    },
    {
      "name": "rel.generate_description",
      "label": "Generate listing description",
      "pack": "real-estate-listings"
    },
    {
      "name": "rel.enhance_photo",
      "label": "Enhance listing photo",
      "pack": "real-estate-listings"
    },
    {
      "name": "sp.generate_post",
      "label": "Generate a post draft",
      "pack": "social-posts"
    },
    {
      "name": "sp.generate_image",
      "label": "Generate a post image",
      "pack": "social-posts"
    }
  ]
} as { nav: { label: string; href: string; icon: string; group: string; pack: string }[]; limits: Record<string, number>; health: { id: string; pack: string }[]; events: unknown[]; operations: unknown[] };
